name: Tests

on:
  push:
    branches: [ master, main ]
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * 1"

jobs:
  test:
    name: Test Extension with Sunbeam
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Test with Sunbeam
        uses: sunbeam-labs/sbx_test_action@v1

      - name: Dump Logs
        shell: bash
        if: always()
        run: tail -n +1 logs/*
      
      - name: Dump Stats
        shell: bash
        if: always()
        run: cat stats/*
