name: Tests

on:
  workflow_dispatch:

jobs:
  test:
    name: Test Extension with Sunbeam
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Test with Sunbeam
        uses: sunbeam-labs/sbx_test_action@main

      - name: Dump Logs
        shell: bash
        if: always()
        run: tail -n +1 logs/*
      
      - name: Dump Stats
        shell: bash
        if: always()
        run: cat stats/*
